### ISSUE TITLE
[BUG] E1810 publishing correctly to Z2M MQTT topic, but nothing happend if dimming up/down

### ISSUE THREAD

**Issue by dummys** [xaviml/controllerx#319]
Hello,

Using a E1810 with tradri light.
Updated everything today, Here is my config:

```
chambre_controller:
  module: controllerx
  class: E1810Controller
  controller: sensor.remote_chambre_action
  integration: z2m
  light: light.tradfri_chambre
```

In the log i see: 

```
 MQTT publish: topic 'zigbee2mqtt/remote_chambre', payload '{"action":"","battery":74,"linkquality":102,"update":{"state":"available"},"update_available":true}'
Info MQTT publish: topic 'zigbee2mqtt/remote_chambre/action', payload 'brightness_down_click'
```

But nothing happend on the light... Can't understand. When toggling ON/off , it is working, but no dimming at all.

**Comment by xaviml** [comment]
Hi @dummys,

Could you restart AppDaemon addon/server, press and hold the brightness button, and then share the logs?

Thank you,
Xavi M.

**Comment by HidYn** [comment]
I have a simular thing using a E1743Controller. It works for one of my switched but the other 8 fail to alter brightness.

Hopefully this log might help?

2021-06-19 19:39:36.408465 INFO hallwaylights_app: 
🤖 Service: light.turn_on
  - entity_id: light.hallway_lights
2021-06-19 19:39:38.872161 INFO hallwaylights_app: 🎮 Button event triggered: `brightness_move_down`
2021-06-19 19:39:38.874566 INFO hallwaylights_app: 🏃 Running `Predefined (hold_brightness_down)` now
2021-06-19 19:39:38.884551 WARNING hallwaylights_app: ------------------------------------------------------------
2021-06-19 19:39:38.884751 WARNING hallwaylights_app: Unexpected error in worker for App hallwaylights_app:
2021-06-19 19:39:38.884954 WARNING hallwaylights_app: Worker Ags: {'id': '07f10ae505224b14afc047c9cd2f28e0', 'name': 'hallwaylights_app', 'objectid': '64f35c60b86344bc923087e6ec97acc3', 'type': 'state', 'function': <bound method Z2MIntegration.state_callback of <cx_core.integration.z2m.Z2MIntegration object at 0x7f11b49e0a00>>, 'attribute': 'state', 'entity': 'sensor.hallway_light_switch_action', 'new_state': 'brightness_move_down', 'old_state': '', 'pin_app': True, 'pin_thread': 2, 'kwargs': {'__thread_id': 'MainThread'}}
2021-06-19 19:39:38.885123 WARNING hallwaylights_app: ------------------------------------------------------------
2021-06-19 19:39:38.885482 WARNING hallwaylights_app: Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/appdaemon/threading.py", line 812, in async_worker
    await funcref(
  File "/config/appdaemon/apps/controllerx/cx_core/integration/z2m.py", line 66, in state_callback
    await self.controller.handle_action(new)
  File "/config/appdaemon/apps/controllerx/cx_core/controller.py", line 335, in handle_action
    await self.call_action(action_key, extra=extra)
  File "/config/appdaemon/apps/controllerx/cx_core/controller.py", line 409, in call_action
    await self.action_timer_callback({"action_key": action_key, "extra": extra})
  File "/config/appdaemon/apps/controllerx/cx_core/controller.py", line 447, in action_timer_callback
    await task
  File "/config/appdaemon/apps/controllerx/cx_core/controller.py", line 465, in call_action_types
    await action_type.run(extra=extra)
  File "/config/appdaemon/apps/controllerx/cx_core/action_type/predefined_action_type.py", line 56, in run
    await action(*args)
  File "/config/appdaemon/apps/controllerx/cx_core/controller.py", line 63, in _action_impl
    await method(controller, *args, **kwargs)
  File "/config/appdaemon/apps/controllerx/cx_core/type/light_controller.py", line 598, in hold
    self.value_attribute = await self.get_value_attribute(attribute)
  File "/config/appdaemon/apps/controllerx/cx_core/type/light_controller.py", line 537, in get_value_attribute
    raise ValueError(
ValueError: Value for `brightness` attribute could not be retrieved from `light.hallway_lights`. Check the FAQ to know more about this error: https://xaviml.github.io/controllerx/faq
2021-06-19 19:39:38.885617 WARNING hallwaylights_app: ------------------------------------------------------------
2021-06-19 19:39:41.551557 INFO alisroomlights_app: 🎮 Button event triggered: `on`
2021-06-19 19:39:41.553688 INFO alisroomlights_app: 🏃 Running `Predefined (on)` now
2021-06-19 19:39:41.556608 INFO alisroomlights_app: 
🤖 Service: light.turn_on
  - entity_id: light.ali_s_bedroom_lights
2021-06-19 19:39:41.654062 INFO hallwaylights_app: 🎮 Button event triggered: `brightness_stop`
2021-06-19 19:39:41.656157 INFO hallwaylights_app: 🏃 Running `Predefined (release)` now
2021-06-19 19:39:42.588819 INFO hallwaylights_app: 🎮 Button event triggered: `brightness_move_down`
2021-06-19 19:39:42.592661 WARNING hallwaylights_app: There is already an action executing for `brightness_move_down`. If you want a different behaviour change `mode` parameter, the default value is `single`.
2021-06-19 19:39:42.859809 INFO hallwaylights_app: 🎮 Button event triggered: `brightness_stop`
2021-06-19 19:39:42.861668 INFO hallwaylights_app: 🏃 Running `Predefined (release)` now
2021-06-19 19:39:43.346597 INFO hallwaylights_app: 🎮 Button event triggered: `off`
2021-06-19 19:39:43.348825 INFO hallwaylights_app: 🏃 Running `Predefined (off)` now
2021-06-19 19:39:43.351763 INFO hallwaylights_app: 
🤖 Service: light.turn_off
  - entity_id: light.hallway_lights
2021-06-19 19:39:44.012001 INFO alisroomlights_app: 🎮 Button event triggered: `off`
2021-06-19 19:39:44.014588 INFO alisroomlights_app: 🏃 Running `Predefined (off)` now
2021-06-19 19:39:44.018240 INFO alisroomlights_app: 
🤖 Service: light.turn_off


Thank you

**Comment by xaviml** [comment]
Hi @HidYn,

As the error indicates ControllerX cannot read the brightness attribute from `light.hallway_lights`. This is probably because `light.hallway_lights` is a light group. If that is the case, ControllerX does not support Light Group as explained in [FAQ#4](https://xaviml.github.io/controllerx/faq). This is not because of ControllerX, but a problem from Light Group integration from HA. It does not show correctly `supported_features` attribute at times, this is why I recommend using the group integration (the generic one).

However, from ControllerX v4.12.0 you can override the value of `supported_features` from ControllerX config like the following:

```yaml
hallwaylights_app:
  module: controllerx
  class: E1743Controller
  controller: sensor.hallway_light_switch_action
  integration: z2m
  light: light.hallway_lights
  supported_features: 191
```

You can read about this value [here](https://xaviml.github.io/controllerx/start/type-configuration#supported_features-field).

Regards,
Xavi M.

**Comment by dummys** [comment]
> Hi @dummys,
> 
> Could you restart AppDaemon addon/server, press and hold the brightness button, and then share the logs?
> 
> Thank you,
> Xavi M.

sure will do it tonight if I have time.

**Comment by HidYn** [comment]
> 
> 
> Hi @HidYn,
> 
> As the error indicates ControllerX cannot read the brightness attribute from `light.hallway_lights`. This is probably because `light.hallway_lights` is a light group. If that is the case, ControllerX does not support Light Group as explained in [FAQ#4](https://xaviml.github.io/controllerx/faq). This is not because of ControllerX, but a problem from Light Group integration from HA. It does not show correctly `supported_features` attribute at times, this is why I recommend using the group integration (the generic one).
> 
> However, from ControllerX v4.12.0 you can override the value of `supported_features` from ControllerX config like the following:
> 
> ```yaml
> hallwaylights_app:
>   module: controllerx
>   class: E1743Controller
>   controller: sensor.hallway_light_switch_action
>   integration: z2m
>   light: light.hallway_lights
>   supported_features: 191
> ```
> 
> You can read about this value [here](https://xaviml.github.io/controllerx/start/type-configuration#supported_features-field).
> 
> Regards,
> Xavi M.

Of course! Helps if I read the FAQ I'm so sorry!

Thanks for pointing that out.

**Comment by HidYn** [comment]
Tried using generic groups and still get the error so I then tried adding the supported features line and sadly still the same.

group:
  hallwaylights:
    name: Hallway Lights
    entities:
      - light.hallway_lamp
      - light.hallway_light

hallwaylights_app:
  module: controllerx
  class: E1743Controller
  controller: sensor.hallway_light_switch_action
  integration: z2m
  light: group.hallwaylights
  supported_features: 191



```
2021-06-24 19:21:50.983816 WARNING hallwaylights_app: ------------------------------------------------------------
2021-06-24 19:21:53.625806 INFO hallwaylights_app: 🎮 Button event triggered: `brightness_stop`
2021-06-24 19:21:53.627465 INFO hallwaylights_app: 🏃 Running `Predefined (release)` now
2021-06-24 19:21:54.717894 INFO hallwaylights_app: 🎮 Button event triggered: `brightness_move_down`
2021-06-24 19:21:54.720311 INFO hallwaylights_app: 🏃 Running `Predefined (hold_brightness_down)` now
2021-06-24 19:21:54.732259 WARNING hallwaylights_app: ------------------------------------------------------------
2021-06-24 19:21:54.732493 WARNING hallwaylights_app: Unexpected error in worker for App hallwaylights_app:
2021-06-24 19:21:54.732651 WARNING hallwaylights_app: Worker Ags: {'id': 'dae26836ff2f4a2cb3a1a6b13538ebfc', 'name': 'hallwaylights_app', 'objectid': '07013d65a59c4e2ab2465ebc1963c7c2', 'type': 'state', 'function': <bound method Z2MIntegration.state_callback of <cx_core.integration.z2m.Z2MIntegration object at 0x7fa18d0a0700>>, 'attribute': 'state', 'entity': 'sensor.hallway_light_switch_action', 'new_state': 'brightness_move_down', 'old_state': 'None', 'pin_app': True, 'pin_thread': 1, 'kwargs': {'__thread_id': 'MainThread'}}
2021-06-24 19:21:54.732794 WARNING hallwaylights_app: ------------------------------------------------------------
2021-06-24 19:21:54.733175 WARNING hallwaylights_app: Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/appdaemon/threading.py", line 812, in async_worker
    await funcref(
  File "/config/appdaemon/apps/controllerx/cx_core/integration/z2m.py", line 66, in state_callback
    await self.controller.handle_action(new)
  File "/config/appdaemon/apps/controllerx/cx_core/controller.py", line 335, in handle_action
    await self.call_action(action_key, extra=extra)
  File "/config/appdaemon/apps/controllerx/cx_core/controller.py", line 409, in call_action
    await self.action_timer_callback({"action_key": action_key, "extra": extra})
  File "/config/appdaemon/apps/controllerx/cx_core/controller.py", line 447, in action_timer_callback
    await task
  File "/config/appdaemon/apps/controllerx/cx_core/controller.py", line 465, in call_action_types
    await action_type.run(extra=extra)
  File "/config/appdaemon/apps/controllerx/cx_core/action_type/predefined_action_type.py", line 56, in run
    await action(*args)
  File "/config/appdaemon/apps/controllerx/cx_core/controller.py", line 63, in _action_impl
    await method(controller, *args, **kwargs)
  File "/config/appdaemon/apps/controllerx/cx_core/type/light_controller.py", line 598, in hold
    self.value_attribute = await self.get_value_attribute(attribute)
  File "/config/appdaemon/apps/controllerx/cx_core/type/light_controller.py", line 537, in get_value_attribute
    raise ValueError(
ValueError: Value for `brightness` attribute could not be retrieved from `group.hallwaylights`. Check the FAQ to know more about this error: https://xaviml.github.io/controllerx/faq
2021-06-24 19:21:54.733328 WARNING hallwaylights_app: ------------------------------------------------------------
2021-06-24 19:21:56.691821 INFO hallwaylights_app: 🎮 Button event triggered: `brightness_stop`
2021-06-24 19:21:56.694481 INFO hallwaylights_app: 🏃 Running `Predefined (release)` now
2021-06-24 19:21:58.759157 INFO hallwaylights_app: 🎮 Button event triggered: `off`
2021-06-24 19:21:58.761680 INFO hallwaylights_app: 🏃 Running `Predefined (off)` now
```

Really appreciate the help - any other ideas?

**Comment by xaviml** [comment]
Hi @HidYn,

Could you please try the individual lights (light.hallway_lamp and light.hallway_light) and see if it works? Also, could you check in the logs which ControllerX version you are running?

Regards,
Xavi M.

**Comment by xaviml** [comment]
Hi all,

I have released ControllerX [v4.14.0](https://github.com/xaviml/controllerx/releases/tag/v4.14.0). This release contains a change on how ControllerX handles group entities like Light Groups or others. You can read more about it [here](https://xaviml.github.io/controllerx/advanced/entity-groups). This means that this problem might have disappeared with the new version, however, let me know if you are still experimenting issues with it. If so, please attach in the comment the AppDaemon logs so I can see what are the problems.

Regards,

**Comment by HidYn** [comment]
Sorry @xaviml I will test tomorrow I've been away for a week or so.

Will get back to you and thanks for this :)

**Comment by HidYn** [comment]
Still having issues.

I have not changed back to a light group yet and am still using just groups.

`🤖 Service: light.turn_on
  - entity_id: group.denlights
  - brightness: 177.40
  - transition: 0.35
2021-07-11 12:19:35.168400 INFO denlights_app: 
🤖 Service: light.turn_on
  - entity_id: group.denlights
  - brightness: 202.80
  - transition: 0.35
2021-07-11 12:19:35.751886 INFO denlights_app: 
🤖 Service: light.turn_on
  - entity_id: group.denlights
  - brightness: 228.20
  - transition: 0.35
2021-07-11 12:19:36.314385 INFO denlights_app: 
🤖 Service: light.turn_on
  - entity_id: group.denlights
  - brightness: 253.60
  - transition: 0.35
2021-07-11 12:19:36.853277 INFO denlights_app: 
🤖 Service: light.turn_on
  - entity_id: group.denlights
  - brightness: 255
  - transition: 0.35
2021-07-11 12:19:37.373683 INFO denlights_app: 🎮 Button event triggered: `brightness_stop`
2021-07-11 12:19:37.386546 INFO denlights_app: 🏃 Running `Predefined (release)` now
2021-07-11 12:19:39.992661 INFO hallwaylights_app: 🎮 Button event triggered: `on`
2021-07-11 12:19:39.994936 INFO hallwaylights_app: 🏃 Running `Predefined (on)` now
2021-07-11 12:19:40.000176 INFO hallwaylights_app: 
🤖 Service: light.turn_on
  - entity_id: group.hallwaylights
2021-07-11 12:19:42.526886 INFO hallwaylights_app: 🎮 Button event triggered: `brightness_move_down`
2021-07-11 12:19:42.530812 INFO hallwaylights_app: 🏃 Running `Predefined (hold_brightness_down)` now
2021-07-11 12:19:42.537566 WARNING hallwaylights_app: ------------------------------------------------------------
2021-07-11 12:19:42.538583 WARNING hallwaylights_app: Unexpected error in worker for App hallwaylights_app:
2021-07-11 12:19:42.539469 WARNING hallwaylights_app: Worker Ags: {'id': 'dc64bedb3f674cadae7ae8edb39b7dc8', 'name': 'hallwaylights_app', 'objectid': '7a85f5ccce86428ab44ed68216bfab47', 'type': 'state', 'function': <bound method Z2MIntegration.state_callback of <cx_core.integration.z2m.Z2MIntegration object at 0x7f80549a5a60>>, 'attribute': 'state', 'entity': 'sensor.hallway_light_switch_action', 'new_state': 'brightness_move_down', 'old_state': 'None', 'pin_app': True, 'pin_thread': 1, 'kwargs': {'__thread_id': 'MainThread'}}
2021-07-11 12:19:42.540367 WARNING hallwaylights_app: ------------------------------------------------------------
2021-07-11 12:19:42.541441 WARNING hallwaylights_app: Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/appdaemon/threading.py", line 812, in async_worker
    await funcref(
  File "/config/appdaemon/apps/controllerx/cx_core/integration/z2m.py", line 66, in state_callback
    await self.controller.handle_action(new)
  File "/config/appdaemon/apps/controllerx/cx_core/controller.py", line 347, in handle_action
    await self.call_action(action_key, extra=extra)
  File "/config/appdaemon/apps/controllerx/cx_core/controller.py", line 421, in call_action
    await self.action_timer_callback({"action_key": action_key, "extra": extra})
  File "/config/appdaemon/apps/controllerx/cx_core/controller.py", line 459, in action_timer_callback
    await task
  File "/config/appdaemon/apps/controllerx/cx_core/controller.py", line 477, in call_action_types
    await action_type.run(extra=extra)
  File "/config/appdaemon/apps/controllerx/cx_core/action_type/predefined_action_type.py", line 115, in run
    await action(*positional, **action_args)
  File "/config/appdaemon/apps/controllerx/cx_core/controller.py", line 64, in _action_impl
    await method(controller, *args, **kwargs)
  File "/config/appdaemon/apps/controllerx/cx_core/type/light_controller.py", line 610, in hold
    self.value_attribute = await self.get_value_attribute(attribute)
  File "/config/appdaemon/apps/controllerx/cx_core/type/light_controller.py", line 549, in get_value_attribute
    raise ValueError(
ValueError: Value for `brightness` attribute could not be retrieved from `light.hallway_lamp`. Check the FAQ to know more about this error: https://xaviml.github.io/controllerx/faq
2021-07-11 12:19:42.547381 WARNING hallwaylights_app: ------------------------------------------------------------
2021-07-11 12:19:46.740706 INFO hallwaylights_app: 🎮 Button event triggered: `brightness_stop`
2021-07-11 12:19:46.742635 INFO hallwaylights_app: 🏃 Running `Predefined (release)` now
2021-07-11 12:19:47.706899 INFO hallwaylights_app: 🎮 Button event triggered: `brightness_move_down`
2021-07-11 12:19:47.711475 INFO hallwaylights_app: 🏃 Running `Predefined (hold_brightness_down)` now
2021-07-11 12:19:47.715992 WARNING hallwaylights_app: ------------------------------------------------------------
2021-07-11 12:19:47.718163 WARNING hallwaylights_app: Unexpected error in worker for App hallwaylights_app:
2021-07-11 12:19:47.718992 WARNING hallwaylights_app: Worker Ags: {'id': 'dc64bedb3f674cadae7ae8edb39b7dc8', 'name': 'hallwaylights_app', 'objectid': '7a85f5ccce86428ab44ed68216bfab47', 'type': 'state', 'function': <bound method Z2MIntegration.state_callback of <cx_core.integration.z2m.Z2MIntegration object at 0x7f80549a5a60>>, 'attribute': 'state', 'entity': 'sensor.hallway_light_switch_action', 'new_state': 'brightness_move_down', 'old_state': 'None', 'pin_app': True, 'pin_thread': 1, 'kwargs': {'__thread_id': 'MainThread'}}
2021-07-11 12:19:47.720057 WARNING hallwaylights_app: ------------------------------------------------------------
2021-07-11 12:19:47.721123 WARNING hallwaylights_app: Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/appdaemon/threading.py", line 812, in async_worker
    await funcref(
  File "/config/appdaemon/apps/controllerx/cx_core/integration/z2m.py", line 66, in state_callback
    await self.controller.handle_action(new)
  File "/config/appdaemon/apps/controllerx/cx_core/controller.py", line 347, in handle_action
    await self.call_action(action_key, extra=extra)
  File "/config/appdaemon/apps/controllerx/cx_core/controller.py", line 421, in call_action
    await self.action_timer_callback({"action_key": action_key, "extra": extra})
  File "/config/appdaemon/apps/controllerx/cx_core/controller.py", line 459, in action_timer_callback
    await task
  File "/config/appdaemon/apps/controllerx/cx_core/controller.py", line 477, in call_action_types
    await action_type.run(extra=extra)
  File "/config/appdaemon/apps/controllerx/cx_core/action_type/predefined_action_type.py", line 115, in run
    await action(*positional, **action_args)
  File "/config/appdaemon/apps/controllerx/cx_core/controller.py", line 64, in _action_impl
    await method(controller, *args, **kwargs)
  File "/config/appdaemon/apps/controllerx/cx_core/type/light_controller.py", line 610, in hold
    self.value_attribute = await self.get_value_attribute(attribute)
  File "/config/appdaemon/apps/controllerx/cx_core/type/light_controller.py", line 549, in get_value_attribute
    raise ValueError(
ValueError: Value for `brightness` attribute could not be retrieved from `light.hallway_lamp`. Check the FAQ to know more about this error: https://xaviml.github.io/controllerx/faq
2021-07-11 12:19:47.721478 WARNING hallwaylights_app: ------------------------------------------------------------
2021-07-11 12:19:48.852634 INFO hallwaylights_app: 🎮 Button event triggered: `brightness_stop`
2021-07-11 12:19:48.860590 INFO hallwaylights_app: 🏃 Running `Predefined (release)` now`

**Comment by xaviml** [comment]
Hi @HidYn,

Thank you for sharing the logs. Could you please try the same config but with `light.hallway_lamp`?

Also, could you share the attributes of `light.hallway_lamp` when the light is on? You can check this in Developer Tools by searching for the entity.

Last question, can you change the brightness of the `light.hallway_lamp` through HA, and which is the integration?

Regards,
Xavi M.

**Comment by dummys** [comment]
hey,
I have the logs for the tradfri.
I updated latest Appdaemon and latest controllerX.
Here is the new log:

```
2021-07-13 21:19:56.273364 INFO chambre_controller: 🎮 ControllerX v4.12.0
2021-07-13 21:19:56.390597 INFO grimpe_controller: 🎮 ControllerX v4.12.0
2021-07-13 21:19:56.490140 INFO veranda_controller: 🎮 ControllerX v4.12.0
2021-07-13 21:20:49.633848 INFO chambre_controller: 🎮 Button event triggered: `toggle`
2021-07-13 21:20:49.647941 INFO chambre_controller: 🏃 Running `Predefined (toggle)` now
2021-07-13 21:20:49.671075 INFO chambre_controller: 
🤖 Service: light.toggle
  - entity_id: light.tradfri_chambre
2021-07-13 21:20:54.811248 INFO chambre_controller: 🎮 Button event triggered: `brightness_down_hold`
2021-07-13 21:20:54.820011 INFO chambre_controller: 🏃 Running `Predefined (hold_brightness_down)` now
2021-07-13 21:20:54.869770 WARNING chambre_controller: ------------------------------------------------------------
2021-07-13 21:20:54.870532 WARNING chambre_controller: Unexpected error in worker for App chambre_controller:
2021-07-13 21:20:54.871202 WARNING chambre_controller: Worker Ags: {'id': 'a4e8f095e1e842928785727b30e1e01d', 'name': 'chambre_controller', 'objectid': '583a54788fd545c18069666279591638', 'type': 'state', 'function': <bound method Z2MIntegration.state_callback of <cx_core.integration.z2m.Z2MIntegration object at 0xffff7f4348e0>>, 'attribute': 'state', 'entity': 'sensor.remote_chambre_action', 'new_state': 'brightness_down_hold', 'old_state': '', 'pin_app': True, 'pin_thread': 1, 'kwargs': {'__thread_id': 'MainThread'}}
2021-07-13 21:20:54.871887 WARNING chambre_controller: ------------------------------------------------------------
2021-07-13 21:20:54.873306 WARNING chambre_controller: Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/appdaemon/threading.py", line 812, in async_worker
    await funcref(
  File "/config/appdaemon/apps/controllerx/cx_core/integration/z2m.py", line 66, in state_callback
    await self.controller.handle_action(new)
  File "/config/appdaemon/apps/controllerx/cx_core/controller.py", line 335, in handle_action
  File "/config/appdaemon/apps/controllerx/cx_core/controller.py", line 409, in call_action
    if handle is not None:
  File "/config/appdaemon/apps/controllerx/cx_core/controller.py", line 447, in action_timer_callback
  File "/config/appdaemon/apps/controllerx/cx_core/controller.py", line 465, in call_action_types
    finally:
  File "/config/appdaemon/apps/controllerx/cx_core/action_type/predefined_action_type.py", line 56, in run
    attr_msg += f" (value given: {action_args[key]})"
  File "/config/appdaemon/apps/controllerx/cx_core/controller.py", line 63, in _action_impl
    if continue_call:
  File "/config/appdaemon/apps/controllerx/cx_core/type/light_controller.py", line 598, in hold
    self.value_attribute = await self.get_value_attribute(attribute)
  File "/config/appdaemon/apps/controllerx/cx_core/type/light_controller.py", line 537, in get_value_attribute
    async def get_value_attribute(self, attribute: str) -> Union[float, int]:
ValueError: Value for `brightness` attribute could not be retrieved from `light.tradfri_chambre`. Check the FAQ to know more about this error: https://xaviml.github.io/controllerx/faq
2021-07-13 21:20:54.873932 WARNING chambre_controller: ------------------------------------------------------------
2021-07-13 21:20:56.367021 INFO chambre_controller: 🎮 Button event triggered: `brightness_down_release`
2021-07-13 21:20:56.375796 INFO chambre_controller: 🏃 Running `Predefined (release)` now
```

**Comment by xaviml** [comment]
Hi @dummys,

According to the logs you are running ControllerX v4.12.0. Did you restart the AppDaemon addon after updating ControllerX? The v4.14.0 should have a new way of treating with Light group integration. The problem is that the `light.tradfri_chambre` does not have a `brightness` attribute in their attribute list. Could you please answer the following questions:

- Is `tradfri_chambre` a group light?
- How is the `tradfri_chambre` integrated?
- Can you change the brightness through HA? If so, does a `brightness` attribute appear in the entity when changing the brightness through HA?
- Could you toggle the light and see if the `brightness` attribute appears?

I am trying to understand what the problem is since 47 as supported features indicates that supports:
- brightness
- color temp
- effect
- flash
- transition

However, I do not understand how the color is working if it is not supported, and the brightness is not working when it is supported.

**Comment by dummys** [comment]
> According to the logs you are running ControllerX v4.12.0. Did you restart the AppDaemon addon after updating ControllerX? 
Yes I restarted it.
> * Is `tradfri_chambre` a group light?
nop
> * How is the `tradfri_chambre` integrated?
z2m
> * Can you change the brightness through HA? If so, does a `brightness` attribute appear in the entity when changing the brightness through HA?
Yes I can change brightness and color_temp too.
> * Could you toggle the light and see if the `brightness` attribute appears?
still not:
```
min_mireds: 250
max_mireds: 454
effect_list:
  - blink
  - breathe
  - okay
  - channel_change
  - finish_effect
  - stop_effect
supported_color_modes:
  - color_temp
linkquality: 138
power_on_behavior: null
update:
  state: available
update_available: true
friendly_name: tradfri_chambre
supported_features: 47
```

**Comment by xaviml** [comment]
Hi @dummys,

This is very interesting. All lights integrated with z2m should have the brightness attribute present. There is no much I can do from my side, however, I recommend you:
- Reset the light and link it again
- Check you are running the latest z2m version
- Check you are running the latest HA

Without the `brightness` attribute, ControllerX does not recognise which brightness should start moving from, and this is why is failing with a message saying that cannot read the `brightness` attribute.

Could you sent me the z2m link of the device? Do you also have another light like that one that works?

Regards,
Xavi M.

**Comment by xaviml** [comment]
It seems you might have the same light as me, and this is what is expected from it when the light is on:

![Screenshot from 2021-07-15 10-16-06](https://user-images.githubusercontent.com/3974003/125753911-019bff89-2b62-4229-8157-015584dd7d46.png)

And this are the attributes when the light is off:

![Screenshot from 2021-07-15 10-16-06](https://user-images.githubusercontent.com/3974003/125753962-50d62da6-db13-4565-87e2-013feaddf1b0.png)

As you can see there is `brightness` attribute when the light is on, and not when is off. This is the expected behaviour for all lights that have brightness support. The only case I have seen different than this is seing the `brightness` as well when the light is off, but that is okay. The problem is when the `brightness` is not present when the light is on.

Regards,

**Comment by dummys** [comment]
> Hi @dummys,
> 
> This is very interesting. All lights integrated with z2m should have the brightness attribute present. There is no much I can do from my side, however, I recommend you:
> 
> * Reset the light and link it again
> * Check you are running the latest z2m version

latest version

> * Check you are running the latest HA

latest version
> Without the `brightness` attribute, ControllerX does not recognise which brightness should start moving from, and this is why is failing with a message saying that cannot read the `brightness` attribute.

when its on attribute:

````
min_mireds: 250
max_mireds: 454
effect_list:
  - blink
  - breathe
  - okay
  - channel_change
  - finish_effect
  - stop_effect
supported_color_modes:
  - color_temp
color_mode: color_temp
brightness: 134
color_temp: 321
linkquality: 138
power_on_behavior: null
update:
  state: available
update_available: true
friendly_name: tradfri_chambre
supported_features: 47
````

> Could you sent me the z2m link of the device? Do you also have another light like that one that works?

https://www.zigbee2mqtt.io/devices/LED1732G11.html#ikea-led1732g11

**Comment by xaviml** [comment]
I see that brightness is there. Is the error still popping up when pressing the controller and the light is on? (Assuming the brightness atrribute is there)

**Comment by dummys** [comment]
Yes error still there. As you asked me to remove it, I have removed it using z2m, and joined again. When the light is on I get this in state:

```
min_mireds: 250
max_mireds: 454
effect_list:
  - blink
  - breathe
  - okay
  - channel_change
  - finish_effect
  - stop_effect
supported_color_modes:
  - color_temp
color_mode: unknown
linkquality: 135
power_on_behavior: null
friendly_name: tradfri_chambre
supported_features: 47
```

**Comment by xaviml** [comment]
And what about the attributes you sent before? The brightness was there.

I will double check my firmware later on, but I believe I have the same lightbulb.

Do you experience the same with other lights? Or the others have the brightness present when the light is on?

**Comment by dummys** [comment]
Hmm yes  I don't get brightness on hue too ...

**Comment by xaviml** [comment]
Interesting.. so the Philips one works well with your ControllerX config, right?

I have checked my LED1732G11 light, and I am on firmware version 2.0.023. Could you try to update the firmware through z2m?

Regards,
Xavi M.

**Comment by xaviml** [comment]
Closing this ticket since there is no activity.
